kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/mf-zoom/ci

steps:
  - name: report
    image: golang
    commands:
      - mkdir -p /var/reports
      - go get
      - go get github.com/360EntSecGroup-Skylar/goreporter
      - goreporter -p ./ -f html -r /var/reports/
  - name: build
    image: node
    commands:
    - npm install
    - npm test 
